name: Feature Request
description: Request a new feature or enhancement
title: "[Feature]: "
labels: ["type:feature", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the details below.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Brief description of the feature
      placeholder: What should this feature do?
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: Background
      description: Why is this feature needed? What problem does it solve?
      placeholder: Explain the context and motivation

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know when this is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Any implementation guidance or considerations

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system does this affect?
      options:
        - API (Backend)
        - UI (Frontend)
        - Telegram Integration
        - Download/Import
        - Database
        - Docker/Deployment
        - Multiple/Unsure
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex is this feature?
      options:
        - Small (< 1 day)
        - Medium (1-3 days)
        - Large (> 3 days)
        - Unknown
