"""initial_schema

Revision ID: 88582f2cba2e
Revises: 
Create Date: 2025-12-29 22:32:16.409656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88582f2cba2e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('telegram_peer_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('invite_link', sa.String(length=512), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('backfill_mode', sa.Enum('ALL_HISTORY', 'LAST_N_MESSAGES', 'LAST_N_DAYS', name='backfillmode'), nullable=False),
    sa.Column('backfill_value', sa.Integer(), nullable=False),
    sa.Column('download_mode', sa.Enum('DOWNLOAD_ALL', 'DOWNLOAD_ALL_NEW', 'MANUAL', name='downloadmode'), nullable=False),
    sa.Column('library_template_override', sa.String(length=512), nullable=True),
    sa.Column('title_source_override', sa.Enum('CAPTION', 'FILENAME', 'MANUAL', name='titlesource'), nullable=True),
    sa.Column('designer_source_override', sa.Enum('CAPTION', 'CHANNEL', 'MANUAL', name='designersource'), nullable=True),
    sa.Column('last_ingested_message_id', sa.Integer(), nullable=True),
    sa.Column('last_backfill_checkpoint', sa.Integer(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_peer_id')
    )
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.create_index('ix_channels_enabled_sync', ['is_enabled', 'last_sync_at'], unique=False)

    op.create_table('designs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_title', sa.String(length=512), nullable=False),
    sa.Column('canonical_designer', sa.String(length=255), nullable=False),
    sa.Column('multicolor', sa.Enum('UNKNOWN', 'SINGLE', 'MULTI', name='multicolorstatus'), nullable=False),
    sa.Column('status', sa.Enum('DISCOVERED', 'WANTED', 'DOWNLOADING', 'DOWNLOADED', 'ORGANIZED', name='designstatus'), nullable=False),
    sa.Column('primary_file_types', sa.String(length=255), nullable=True),
    sa.Column('total_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('title_override', sa.String(length=512), nullable=True),
    sa.Column('designer_override', sa.String(length=255), nullable=True),
    sa.Column('multicolor_override', sa.Enum('UNKNOWN', 'SINGLE', 'MULTI', name='multicolorstatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('designs', schema=None) as batch_op:
        batch_op.create_index('ix_designs_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_designs_designer', ['canonical_designer'], unique=False)
        batch_op.create_index('ix_designs_multicolor', ['multicolor'], unique=False)
        batch_op.create_index('ix_designs_status', ['status'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('design_tags',
    sa.Column('design_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.Enum('AUTO', 'MANUAL', name='tagsource'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('design_id', 'tag_id')
    )
    with op.batch_alter_table('design_tags', schema=None) as batch_op:
        batch_op.create_index('ix_design_tags_design_id', ['design_id'], unique=False)
        batch_op.create_index('ix_design_tags_tag_id', ['tag_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('BACKFILL_CHANNEL', 'SYNC_CHANNEL_LIVE', 'DOWNLOAD_DESIGN', 'EXTRACT_ARCHIVE', 'ANALYZE_3MF', 'GENERATE_RENDER', 'IMPORT_TO_LIBRARY', 'DEDUPE_RECONCILE', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELED', name='jobstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=True),
    sa.Column('design_id', sa.String(length=36), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('progress_current', sa.Integer(), nullable=True),
    sa.Column('progress_total', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_channel_id', ['channel_id'], unique=False)
        batch_op.create_index('ix_jobs_design_id', ['design_id'], unique=False)
        batch_op.create_index('ix_jobs_status_type_priority', ['status', 'type', 'priority'], unique=False)

    op.create_table('telegram_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('telegram_message_id', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('caption_text', sa.Text(), nullable=True),
    sa.Column('caption_text_normalized', sa.Text(), nullable=True),
    sa.Column('has_media', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'telegram_message_id', name='uq_channel_message')
    )
    with op.batch_alter_table('telegram_messages', schema=None) as batch_op:
        batch_op.create_index('ix_telegram_messages_channel_date', ['channel_id', 'date_posted'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('telegram_file_id', sa.String(length=255), nullable=True),
    sa.Column('telegram_unique_file_id', sa.String(length=255), nullable=True),
    sa.Column('media_type', sa.Enum('DOCUMENT', 'PHOTO', 'VIDEO', 'OTHER', name='mediatype'), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=127), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('ext', sa.String(length=32), nullable=True),
    sa.Column('is_candidate_design_file', sa.Boolean(), nullable=False),
    sa.Column('download_status', sa.Enum('NOT_DOWNLOADED', 'DOWNLOADING', 'DOWNLOADED', 'FAILED', name='attachmentdownloadstatus'), nullable=False),
    sa.Column('download_path', sa.String(length=1024), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['telegram_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index('ix_attachments_candidate', ['is_candidate_design_file'], unique=False)
        batch_op.create_index('ix_attachments_message_id', ['message_id'], unique=False)
        batch_op.create_index('ix_attachments_sha256', ['sha256'], unique=False)

    op.create_table('design_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('design_id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('source_rank', sa.Integer(), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('caption_snapshot', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['telegram_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'message_id', name='uq_design_source_message')
    )
    with op.batch_alter_table('design_sources', schema=None) as batch_op:
        batch_op.create_index('ix_design_sources_design_id', ['design_id'], unique=False)

    op.create_table('design_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('design_id', sa.String(length=36), nullable=False),
    sa.Column('source_attachment_id', sa.String(length=36), nullable=True),
    sa.Column('relative_path', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('ext', sa.String(length=32), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('file_kind', sa.Enum('MODEL', 'ARCHIVE', 'IMAGE', 'OTHER', name='filekind'), nullable=False),
    sa.Column('model_kind', sa.Enum('STL', 'THREE_MF', 'OBJ', 'STEP', 'UNKNOWN', name='modelkind'), nullable=False),
    sa.Column('is_from_archive', sa.Boolean(), nullable=False),
    sa.Column('archive_parent_id', sa.String(length=36), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['archive_parent_id'], ['design_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_attachment_id'], ['attachments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('design_files', schema=None) as batch_op:
        batch_op.create_index('ix_design_files_design_id', ['design_id'], unique=False)
        batch_op.create_index('ix_design_files_ext_kind', ['ext', 'file_kind'], unique=False)
        batch_op.create_index('ix_design_files_sha256', ['sha256'], unique=False)

    op.create_table('preview_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('design_id', sa.String(length=36), nullable=False),
    sa.Column('source_attachment_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.Enum('TELEGRAM_IMAGE', 'THREE_MF_EMBEDDED', 'RENDERED', name='previewkind'), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_attachment_id'], ['attachments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('preview_assets', schema=None) as batch_op:
        batch_op.create_index('ix_preview_assets_design_kind', ['design_id', 'kind'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preview_assets', schema=None) as batch_op:
        batch_op.drop_index('ix_preview_assets_design_kind')

    op.drop_table('preview_assets')
    with op.batch_alter_table('design_files', schema=None) as batch_op:
        batch_op.drop_index('ix_design_files_sha256')
        batch_op.drop_index('ix_design_files_ext_kind')
        batch_op.drop_index('ix_design_files_design_id')

    op.drop_table('design_files')
    with op.batch_alter_table('design_sources', schema=None) as batch_op:
        batch_op.drop_index('ix_design_sources_design_id')

    op.drop_table('design_sources')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index('ix_attachments_sha256')
        batch_op.drop_index('ix_attachments_message_id')
        batch_op.drop_index('ix_attachments_candidate')

    op.drop_table('attachments')
    with op.batch_alter_table('telegram_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_telegram_messages_channel_date')

    op.drop_table('telegram_messages')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status_type_priority')
        batch_op.drop_index('ix_jobs_design_id')
        batch_op.drop_index('ix_jobs_channel_id')

    op.drop_table('jobs')
    with op.batch_alter_table('design_tags', schema=None) as batch_op:
        batch_op.drop_index('ix_design_tags_tag_id')
        batch_op.drop_index('ix_design_tags_design_id')

    op.drop_table('design_tags')
    op.drop_table('tags')
    with op.batch_alter_table('designs', schema=None) as batch_op:
        batch_op.drop_index('ix_designs_status')
        batch_op.drop_index('ix_designs_multicolor')
        batch_op.drop_index('ix_designs_designer')
        batch_op.drop_index('ix_designs_created_at')

    op.drop_table('designs')
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_index('ix_channels_enabled_sync')

    op.drop_table('channels')
    # ### end Alembic commands ###
