"""add_external_metadata_and_design_authority

Revision ID: 95d0f01bdc40
Revises: 88582f2cba2e
Create Date: 2025-12-30 10:36:05.366145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d0f01bdc40'
down_revision: Union[str, Sequence[str], None] = '88582f2cba2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_metadata_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('design_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.Enum('THANGS', 'PRINTABLES', 'THINGIVERSE', name='externalsourcetype'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('external_url', sa.String(length=1024), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('match_method', sa.Enum('LINK', 'TEXT', 'GEOMETRY', 'MANUAL', name='matchmethod'), nullable=False),
    sa.Column('is_user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('fetched_title', sa.String(length=512), nullable=True),
    sa.Column('fetched_designer', sa.String(length=255), nullable=True),
    sa.Column('fetched_tags', sa.Text(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('design_id', 'source_type', name='uq_design_source_type')
    )
    with op.batch_alter_table('external_metadata_sources', schema=None) as batch_op:
        batch_op.create_index('ix_external_metadata_sources_external_id', ['external_id'], unique=False)
        batch_op.create_index('ix_external_metadata_sources_source_type', ['source_type'], unique=False)

    with op.batch_alter_table('designs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_authority', sa.Enum('TELEGRAM', 'THANGS', 'PRINTABLES', 'USER', name='metadataauthority'), nullable=False, server_default='TELEGRAM'))
        batch_op.add_column(sa.Column('metadata_confidence', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('designs', schema=None) as batch_op:
        batch_op.drop_column('metadata_confidence')
        batch_op.drop_column('metadata_authority')

    with op.batch_alter_table('external_metadata_sources', schema=None) as batch_op:
        batch_op.drop_index('ix_external_metadata_sources_source_type')
        batch_op.drop_index('ix_external_metadata_sources_external_id')

    op.drop_table('external_metadata_sources')
    # ### end Alembic commands ###
