"""add_split_archive_columns

Revision ID: da92e25e25a7
Revises: 95d0f01bdc40
Create Date: 2025-12-30 14:19:06.547231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da92e25e25a7'
down_revision: Union[str, Sequence[str], None] = '95d0f01bdc40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('designs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_split_archive', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('split_archive_base_name', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('detected_parts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expected_parts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('designs', schema=None) as batch_op:
        batch_op.drop_column('expected_parts')
        batch_op.drop_column('detected_parts')
        batch_op.drop_column('split_archive_base_name')
        batch_op.drop_column('is_split_archive')

    # ### end Alembic commands ###
